# Generated by Django 5.2.6 on 2025-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_pubkey', models.CharField(max_length=50)),
                ('recepient_pubkey', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=256)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=256)),
                ('generated', models.BooleanField(default=False)),
                ('isMined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepient_pubkey', models.CharField(max_length=256)),
                ('sender_pubkey', models.CharField(max_length=256)),
                ('amount', models.PositiveIntegerField()),
                ('spent', models.BooleanField(default=False)),
                ('isMined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=256)),
                ('previous_block_hash', models.CharField(max_length=256)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.PositiveIntegerField()),
                ('transactions', models.ManyToManyField(to='main.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='inputs',
            field=models.ManyToManyField(related_name='input_transactions', to='main.utxo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='outputs',
            field=models.ManyToManyField(related_name='output_transactions', to='main.utxo'),
        ),
    ]
