# Generated by Django 5.2.6 on 2025-09-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recepient_pubkey',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_pubkey',
            field=models.CharField(max_length=250),
        ),
    ]
