# Generated by Django 5.2.6 on 2025-10-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transaction_recepient_pubkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='previous_block_hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
