# Generated by Django 5.2.6 on 2025-10-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_block_previous_block_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
