# Generated by Django 5.2.6 on 2025-10-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_node_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='outputs',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recepient_pubkey',
        ),
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.block'),
        ),
        migrations.AddField(
            model_name='utxo',
            name='hash',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='utxo',
            name='input_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs', to='main.transaction'),
        ),
        migrations.AddField(
            model_name='utxo',
            name='output_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='main.transaction'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['ip'], name='main_node_ip_e398fd_idx'),
        ),
    ]
