# Generated by Django 5.2.6 on 2025-10-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_block_transactions_remove_transaction_inputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utxo',
            name='hash',
            field=models.CharField(blank=True, null=True),
        ),
    ]
