# Generated by Django 5.2.6 on 2025-10-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_utxo_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.block'),
        ),
        migrations.AlterField(
            model_name='utxo',
            name='input_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs', to='main.transaction'),
        ),
        migrations.AlterField(
            model_name='utxo',
            name='output_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='main.transaction'),
        ),
    ]
