# Generated by Django 5.2.6 on 2025-11-01 21:28

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_transaction_block_alter_utxo_input_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utxo',
            name='amount',
            field=models.FloatField(validators=[main.validators.validate_positive]),
        ),
    ]
