# Generated by Django 5.2.6 on 2025-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_utxo_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='miner_pubkey',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
